=== knu-3-tochanenko/OOP/Lab 2/src/main/resources/Greenhouse.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="breedingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="flowers"/>
            <xs:enumeration value="stalk"/>
            <xs:enumeration value="seeds"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="soilType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="podzolic"/>
            <xs:enumeration value="unpaved"/>
            <xs:enumeration value="sod podzolic"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[\dA-F]{6}([\dA-F][\dA-F])?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="greenhouse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plant" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="name" type="xs:string"/>

                            <xs:element name="soil">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="soilType"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="origin" type="xs:string"/>

                            <xs:element name="visual-parameters">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="stem-color" type="color"/>

                                        <xs:element name="leaf-color" type="color"/>

                                        <xs:element name="average-size" type="xs:float"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="growing-tips">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="temperature" type="xs:int"/>
                                        <xs:element name="needs-light" type="xs:boolean"/>
                                        <xs:element name="watering" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="breeding">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="breedingType"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== knu-3-tochanenko/OOP/Sem 5/Lab 2/src/main/resources/GreenhouseWrong.xml
<?xml version="1.0" encoding="UTF-8" ?>
<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="Greenhouse.xsd">

    <plant id="0001">
        <name>rose</name>
        <soil>unpaved</soil>
        <origin>Ukraine</origin>
        <visual-parameters>
            <stem-color>M00FF00</stem-color>
            <leaf-color>#FF0000</leaf-color>
            <average-size>15.6</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25</temperature>
            <needs-light></needs-light>
            <watering>100</watering>
        </growing-tips>
        <breeding>stalk</breeding>
    </plant>

    <plant id="0002">
        <name>tulip</name>
        <soil>podzolic</soil>
        <origin>Netherlands</origin>
        <visual-parameters>
            <stem-color>#88FF00</stem-color>
            <leaf-color>#FF8800</leaf-color>
            <average-size>12.3</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>30</temperature>
            <needs-light>false</needs-light>
            <watering>300</watering>
        </growing-tips>
        <breeding>seeds</breeding>
    </plant>

    <plant id="0003">
        <name>dandilion</name>
        <soil>sod podzolic</soil>
        <origin>Germany</origin>
        <visual-parameters>
            <stem-color>#880044</stem-color>
            <leaf-color>d</leaf-color>
            <average-size>5.0</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>15</temperature>
            <needs-light>true</needs-light>
            <watering>50</watering>
        </growing-tips>
        <breeding>flowers</breeding>
    </plant>

</greenhouse>
